name: SpicyAlert

on:
  schedule:
    - cron: '0 * * * *'   # Runs at the top of every hour (UTC)
  workflow_dispatch:

jobs:
  run-spicyalert:
    runs-on: ubuntu-latest
    environment: Spicy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run SpicyAlert
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: go run fanfa/SpicyAlert/main.go