name: SpicyAlert Checker

on:
  schedule:
    - cron: '0 * * * *'   # Runs at the top of every hour (UTC)
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  run-spicyalert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Initialize Go module
        run: go mod init github.com/brunogrigoletti/ConcurTraining
        if: "!exists('go.mod')" # Only runs if go.mod doesn't exist

      - name: Install dependencies (if any)
        run: go mod tidy

      - name: Run SpicyAlert
        run: go run main.go
